# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: leetcode-pp
    url: https://leetcode-solution.cn/
  - name: ninety-one
    url: https://leetcode-solution.cn/91
status-website: # Status website (optional)
  cname: lucifer.ren # Custom domain CNAME
  baseUrl: /status
  name: leetcode-pp status # Status website title
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
